en:
  activerecord:
    attributes:
      user:
        username: Username
        user_type: User Type
        email: Email
        genre: Musical genres
        instruments: Instruments
        searching_for: Searching for
        references: Musical References
        request_message: Request message
        new_password: New password
        password: Password
        current_password: Current password
        last_updater: Last updater
        last_active: Recent activity
        created_at: Created at
        updated_at: Updated at
        birthdate: Birth date
        zip: Zip code
        country: Country
        password_confirmation: Password confirmation
        avatar: Profile picture
        testimonials: "%{user}'s Testimonials"
        location: Location
        youtube_video_id: YouTube Video Id
        visible: Visible
        invisible: Invisible
      testimonial:
        body: Body
        user: User
    models:
      users: Users
      testimonials: Testimonials
      messages: Messages
      search: Search


