en:
  messages:
    delete: Delete
    subject: Subject
    sender: Send by
    from: From
    received: Received on
    sent_on: Sent on
    no_messages: You have no messages
    to: To
    message: Message
    new:
      title: New message
    inbox:
      title: Your Messages
      subtitle: Inbox
      description: 'Your inbox helps you keep your musicians or band infos private'
    sent:
      title: Your Messages
      subtitle: Sent Messages