en:
  users:
    types:
      musician: Musician
      band: Band
      agent: Agent
    musician_infos: Musician Infos
    location: Location
    credentials: Credentials
    index:
      title: Users Listing
      processing_search: Processing search
      no_users: "We couldn't find any users corresponding to you search criterias."
      invite_more_users: Invite more user to Emuzikos and help to make the community grow!
    show:
      title: "%{username}'s profile"
      from: from
      donate: We depend on you! Please consider donate.
      is_looking_for: is looking for a
      to_play: to play
      music: music
      events: Future events
      users_nearby: Other users nearby
    edit:
      title: Edit your profile
      meta_description: "Edit %{username}'s profile page. Musician, band or agents infos"
      profile_complete_notice: "Congratulations, your profile is complete!"
      profile_not_complete_notice: "In order to appear in search results, you need to complete your profile fully (except the media section)."
      visible_notice: "You now appear in search results!"
      invisible_notice: "Make sure you're set as visible in order to appear in search results"
      medias: "Medias (optional)"
      tracks: "Tracks"
      visible_explanation: 'When "visible", you will appear in search results if your profile is complete (except medias). When "invisible", you will be removed you from any search results.'
      instruments_in_band_notice: "If you're a band, list instruments already present in the band"
      form_helpers:
        genre_not_on_list: "Your genre is not in the list?"
        instrument_not_in_list: "Your instrument is not in the list?"
        request_through_dashboard: "Please make a request using the help dashboard"
        personal_infos_advice: "We advice you not to share any personal informations such as email or phone number. Let people contact you using the internal messaging system instead."
        dont_have_a_service_account: "Don't have %{service} account? "
        dont_find_youtube_video_id: "Don't find your Youtube video id?"
      youtube_video_id_help:
        title: How to find your Youtube video id?
        steps:
          first: First go to your youtube video page
          second: "Then copy the id form the page url. That's the text after 'watch?v='"
          third: Paste it in your profile youtube video id field
          fourth: Press update
    contacts:
      title: Contact list
      no_users: "You don't have any contact in your list"
    prefers:
      newsletters: Neswletters
      message_notifications: Message notifications
