##
# Common Settings
common: &default_settings
  version: 1
  site:
    results_per_page: 20
    avatar:
      normal:
        size: 300
      thumb:
        size: 100
      small:
        size: 30

  google:
    analytics:
      enabled: false
      key: UA-4782653-1

  email:
    from: "Emuzikos <boris@emuzikos.com>"
    do_not_reply_from: "Eumzikos <noreply@emuzikos.com>"
  addthis:
    enabled: false

  mailchimp:
    api_key: '613dcd0b1e941fc982eefabed484c3c5-us2'
    list_name: Emuzikos_dev
    list_url: http://eepurl.com/f8qj9
    list_url: http://eepurl.com/eoZDQ

  soundcloud:
    api_key: "eabbf1f936c1dad49fe9e0d38cc34c5f"

  youtube_it:
    api_key: 'AI39si7FayCLoIiujLg3XPJpYYH1kbn4PoEXev-lz3GVY305SkM9EU7weLeNmdRYvRkBFilD1Ms_nj8QNbeS6rDoBxVCpNK21g'

  facebook:
    app_id: '226327037396547'

  mixpanel:
    api_key: 'ba08fcc820faf968fe94d4b7ea74d89c'
  songkick:
    api_key: "cApdrGD0PiCPiJyw"
  social:
    facebook_page_url: "http://www.facebook.com/pages/Emuzikos/169399636456395"

development:
  <<: *default_settings
  google:
    analytics:
      enabled: false
  email:
    from: "Emuzikos <boris@emuzikos.com>"
    do_not_reply_from: "Eumzikos <noreply@emuzikos.com>"

staging:
  <<: *default_settings
  facebook:
    app_id: '242929185733501'
  google:
    analytics:
      enabled: false
  addthis:
    enabled: true
  email:
    from: "Emuzikos <boris@emuzikos.com>"
    do_not_reply_from: "Eumzikos <noreply@emuzikos.com>"

production:
  <<: *default_settings
  facebook:
    app_id: '218956201460694'
  google:
    analytics:
      enabled: true
      key: UA-4782653-1
  addthis:
    enabled: true
  mixpanel:
    api_key: 'd781e333edf9372a90391186604386f5'
  mailchimp:
    api_key: '613dcd0b1e941fc982eefabed484c3c5-us2'
    list_name: Emuzikos
    list_url: http://eepurl.com/eoZDQ

test:
  <<: *default_settings
  google:
    analytics:
      enabled: false

cucumber:
  <<: *default_settings
  google:
    analytics:
      enabled: false
