javascript_compressor: yui

javascripts:
  jquery:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery-ui-1.8.9.custom.min.js
    - public/javascripts/jquery.uniform.min.js
    
  emuzikos:
    - public/javascripts/rails.js
    - public/javascripts/jquery.tipsy.js
    - public/javascripts/application.js

stylesheets:
  common:

    - public/stylesheets/jquery.Jcrop.css
    - public/stylesheets/ui-themes/Aristo/jquery-ui-1.8.7.custom.css
    - public/stylesheets/uniform-themes/uniform.emuzikos.css
    - public/stylesheets/compiled/grid.css
    - public/stylesheets/compiled/text.css    