javascript_compressor: yui

javascripts:
  polyfills:
    - public/javascripts/modernizr-2.0.6.js
  jquery:
    - public/javascripts/jquery-1.5.min.js
    - public/javascripts/jquery-ui-1.8.9.custom.min.js
    - public/javascripts/jquery.uniform.min.js
  statistics:
    - public/javascripts/highcharts.js
  emuzikos:
    - public/javascripts/rails.js
    - public/javascripts/jquery.tipsy.js
    - public/javascripts/jquery.noisy.min.js
    - public/javascripts/gritter/jquery.gritter.min.js  
    - public/javascripts/jquery.masonry.min.js
    - public/javascripts/jquery.simplemodal.1.4.1.min.js
    - public/javascripts/jquery.pageless.js
    - public/javascripts/application.js

stylesheets:
  common:
    - public/stylesheets/jquery.Jcrop.css
    - public/stylesheets/ui-themes/Emuzikos/jquery-ui-1.8.7.custom.css
    - public/stylesheets/uniform-themes/uniform.emuzikos.css
    - public/stylesheets/compiled/grid.css
    - public/stylesheets/compiled/text.css  
    - public/stylesheets/gritter/jquery.gritter.css 
    - public/stylesheets/boxy.css  
  homepage:
    - public/stylesheets/compiled/homepage.css  
  
  