# development:
#   adapter: mysql
#   encoding: ASCII-8BIT
#   reconnect: false
#   database: emuzikos
#   pool: 5
#   username: root
#   password:
#   socket: /tmp/mysql.sock

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: emuzikos
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

# development:
#   adapter: sqlite3
#   database: db/emuzikos_dev.sqlite3
#   pool: 8
#   timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: emuzikos
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: emuzikos_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
