# development:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: emuzikos
#   pool: 5
#   username: root
#   password:
#   socket: /tmp/mysql.sock
# 


development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: emuzikos
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: emuzikos_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
cucumber:
  <<: *test