#
# Format:
#
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production:
  app: emuzikos
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA–2826331–13"

staging:
  app: emuzikos-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"

