development:
  bucket_name: emuzikos-dev
  bucket: emuzikos-dev
  access_key_id: AKIAJWUPX6SF4T3BUQKQ
  secret_access_key: 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

staging:
  bucket_name: emuzikos-staging
  bucket: emuzikos-staging
  access_key_id: AKIAJWUPX6SF4T3BUQKQ
  secret_access_key: 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

test:
  bucket_name: emuzikos-test
  bucket: emuzikos-test
  access_key_id: AKIAJWUPX6SF4T3BUQKQ
  secret_access_key: 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

production:
  bucket_name: emuzikos-production
  bucket: emuzikos-production
  access_key_id: AKIAJWUPX6SF4T3BUQKQ
  secret_access_key: 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
