development:
  bucket_name: emuzikos-dev
  bucket: emuzikos-prod
  access_key_id: AKIAJWUPX6SF4T3BUQKQ
  secret_access_key: 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

test:
  bucket_name: emuzikos-test
  bucket: emuzikos-prod
  access_key_id: AKIAJWUPX6SF4T3BUQKQ
  secret_access_key: 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

production:
  bucket_name: emuzikos-prod
  bucket: emuzikos-prod
  access_key_id: AKIAJWUPX6SF4T3BUQKQ
  secret_access_key: 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
